train_file: ['data/finetune/nlvr_train.json']
val_file: ['data/finetune/nlvr_dev.json']
test_file: ['data/finetune/nlvr_test.json']

image_root: 'images/nlvr2/'

## Vision Encoder
use_clip_vit: True
vision_config: 'configs/config_clipvit_small.json'
image_res: 384
patch_size: 16

## Text Encoder (& Cross Encoder)
text_encoder: 'data/bert-base-uncased'
text_config: 'data/bert-base-uncased/config.json'
text_num_hidden_layers: 6  # 3 for text encoder, 3 for cross encoder


## Training
batch_size: 10
output_attentions: True
output_hidden_states: True
sparsity: 0.25
## Other Settings
optimizer: {opt: adamW, lr: 3e-5,reg_learning_rate: 0.1, weight_decay: 0.01, lr_mult: 2}
schedular: {sched: linear, lr: 3e-5, epochs: 10, num_warmup_steps: 0.1}
L0_schedular: {droprate_init: 0.5,temperature: 0.6667,lagrangian_warmup_epochs: 1}

